name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Vérifier le code
      uses: actions/checkout@v2

    - name: Installer Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        

    - name: Installer les dépendances
      run: npm install
      working-directory: backend

    - name: Donner les permissions d'exécution à vitest
      run: chmod +x node_modules/.bin/vitest
      working-directory: backend

    - name: Exécuter les tests
      run: npm run test
      working-directory: backend
